[package]
name = "couples-app-backend"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
jiff = "0.2"
thiserror = "2.0"
tracing = "0.1"

  [dependencies.sqlx]
  version = "0.8"
  features = [
    "runtime-tokio",
    "sqlite",
  ]

  [dependencies.tokio]
  version = "1.48"
  features = [
    "macros",
    "rt-multi-thread",
    "signal",
  ]

  [dependencies.tracing-subscriber]
  version = "0.3"
  features = [
    "env-filter",
    "json",
  ]
